dependencies:
  # <github_repo>@<version--->are changing continuously need to change according to us>
  - smartcontractkit/chainlink-brownie-contracts@1.2.0
compiler:
  # now need to tell compiler @chainlink comes use the above dependencies
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.2.0'
dotenv: .env
wallets:
  from_key: ${Private_key}
networks:
  goreli:
    eth_usd_price_feed: '0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e' # or i can store it in .env and also i can  reterive it
    verfiy: True
  development:
    verfiy: False